### ISSUE TITLE
request 

### ISSUE THREAD

**Issue by thuka1500** [KhunHtetzNaing/xGetter#1]
mediafire ကိုလည္း ေမွ်ာ္ေနတယ္ 
ဒါနဲ့ README.md ကထပ္ေနတယ္

**Comment by KhunHtetzNaing** [comment]
ဟုတ္ကဲ့ပါ
Readme ကထပ္ေနတာမဟုတ္ပဲ
ေဇာ္ဂ်ီေရာ ယူနီကုဒ္ေရာႏွစ္မ်ိဳးလုပ္ထားလို႔ပါ

**Comment by KhunHtetzNaing** [comment]
ထည့္ေပးလိုက္ျပီေနာ္ 💯
