### ISSUE TITLE
Support for blogger

### ISSUE THREAD

**Issue by superstarbird** [KhunHtetzNaing/xGetter#18]
Your repository is impressive. It would be even more impressive if you had support for blogger videos. I've been looking for an alternative to extracting the video link for weeks, but I'm in a dead end. Maybe you can shed some light.

**Comment by KhunHtetzNaing** [comment]
hey, please give me your video link ?

**Comment by superstarbird** [comment]
It is an example, but all blogger videos links are like this

https://www.blogger.com/video.g?token=AD6v5dwS4_dlu9Lau5KBBbuSTFC1mavePNhKA0JtWTKc6PaF-eVYyjdIobKky8-ONu7seEgrEiz2xrv7bXrSoOJjNhyDp0CwZKjyBoDA88nzDOTB_GoWBWFA2CXDcP9XgIyDQIWkaKBz

**Comment by KhunHtetzNaing** [comment]
It supports 360p only 👎 
I think not good

**Comment by superstarbird** [comment]
Well, 360p isn't that bad, but if you can't add support for Blogger, would adding support for VeryStream and Fembed be possible?

**Comment by KhunHtetzNaing** [comment]
added

**Comment by superstarbird** [comment]
thank u
