### ISSUE TITLE
Not working with Openload anymore

### ISSUE THREAD

**Issue by Smarpit-Singh** [KhunHtetzNaing/xGetter#2]
All other servers work fine but can't get the openload link. Also, try with many VPN's but can't get openload link. Here are the log that i got when using the openload link.

![Untitled](https://user-images.githubusercontent.com/27909804/54283476-2220eb00-45c4-11e9-955a-803fd101f128.png)

**Comment by KhunHtetzNaing** [comment]
can you give me your openload video link ?

**Comment by Smarpit-Singh** [comment]
https://oload.space/f/y2iEeERlQxU

**Comment by KhunHtetzNaing** [comment]
https://chrome.google.com/webstore/detail/openload%20streamango-playe/nnaacnfogloeemgkjfemjonaikedogla

hey plz test it on your chrome and give me feedback

**Comment by Smarpit-Singh** [comment]
## Openload Link works fine without using your extention- 
![image](https://user-images.githubusercontent.com/27909804/54469728-fe2af880-47c1-11e9-977e-79882981a9cc.png)



## But when i use your extention it did not works - 
![image](https://user-images.githubusercontent.com/27909804/54469747-7b566d80-47c2-11e9-9375-cee7387eeb8f.png)

**Comment by lordmen99** [comment]
i have same issue, for openload cant play (extract mp4 url)

**Comment by KhunHtetzNaing** [comment]
Hello @Smarpit-Singh  and @lordmen99 
i just fixed right now, plz use new version 1.4
let me know if working or not
thanks 👍

**Comment by lordmen99** [comment]
Error:Failed to resolve: xGetter

**Comment by KhunHtetzNaing** [comment]
https://github.com/KhunHtetzNaing/xGetter/blob/master/README.md

**Comment by lordmen99** [comment]
working now, thank bro

**Comment by Smarpit-Singh** [comment]
In India, Openload.co domain is blocked. 
I want to replace the response that returned by openload website from "https://openload.co/stream/-----" to "https://oload.club/stream/----" using regex or matcher? 
 Can you help me to get rid of this situation?

**Comment by KhunHtetzNaing** [comment]
@Smarpit-Singh i will update direct link to based on input url

**Comment by Smarpit-Singh** [comment]
I have some questions for you, If you don't mind can we talk on hangout?
