### ISSUE TITLE
Support for Vidstream.top

### ISSUE THREAD

**Issue by CWSUAE** [KhunHtetzNaing/xGetter#23]
link
https://vidstream.top/embed/czkgHKCEnY/?r

**Comment by CWSUAE** [comment]
link 
https://vidstream.top/embed/czkgHKCEnY/?r

**Comment by KhunHtetzNaing** [comment]
404 not found

**Comment by CWSUAE** [comment]
I think this link does not work, they use the time and IP in links

https://vidbom.com/embed-w1c29g57x2v9.html
https://vidshare.tv/embed-6bbn1ew0v6mq.html
https://gounlimited.to/d3r6oyjy63we/[arabseed].Abo.Hafeza.S01.Ep13.720.mp4

Can this server be supported?

**Comment by KhunHtetzNaing** [comment]
added

**Comment by qaeislol** [comment]
Can this server be supported?
https://www.4shared.com/web/embed/file/nRR9cqpUiq.html
https://vidfast.co/embed-9dlohx46m90q.html
https://uqload.com/embed-qxul50oxia7x.html
https://mstream.space/ej8vjpdynieh
