### ISSUE TITLE
If I try to submit an app to the Google Play Store and it contains xGetter, will it be accepted?

### ISSUE THREAD

**Issue by superstarbird** [KhunHtetzNaing/xGetter#24]
I read somewhere about not allowing YouTube-powered ripping apps, but found nothing under the developer console. Could you clarify this doubt? If possible, of course.

**Comment by owaisalam12** [comment]
did your app get accepted on playstore?

**Comment by KhunHtetzNaing** [comment]
I don't know, but this app uses xgetter library
https://play.google.com/store/apps/details?id=com.mtube.movieslibrary
