### ISSUE TITLE
facebook videos live

### ISSUE THREAD

**Issue by KeaMengsrea** [KhunHtetzNaing/xGetter#31]
can't play with facebook live videos although it's finish living

**Comment by tommyzat** [comment]
Do your regular Facebook videos work? I'm getting onError even on those

**Comment by KhunHtetzNaing** [comment]
Don't put video link, if fb video you need to put VIDEO ID

**Comment by tommyzat** [comment]
Thank you! This way it works.

**Comment by owaisalam12** [comment]
does it violate play store policy if i put any app based on xgetter? apart from youtube videos

**Comment by KhunHtetzNaing** [comment]
@owaisalam12 I don't know, but this app uses xgetter library
[https://play.google.com/store/apps/details?id=com.mtube.movieslibrary](https://play.google.com/store/apps/details?id=com.mtube.movieslibrary)
