### ISSUE TITLE
Harmful application to protect Google Play Is there a solution to the problem?

### ISSUE THREAD

**Issue by qaeislol** [KhunHtetzNaing/xGetter#39]
Harmful application to protect Google Play Is there a solution to the problem?
![029b9d2b-6378-4fdb-9162-4a029dfd4ac1](https://user-images.githubusercontent.com/65055003/81510502-c57da500-931a-11ea-8253-797ab5caaa8b.jpg)

**Comment by KhunHtetzNaing** [comment]
Turn off improve harmful app detection in Play Protect settings Or publish your app on play store

**Comment by KhunHtetzNaing** [comment]
hello, I released new version 3.0 and I remove the external javascript file and changes class name to LowCostVideo.
I think will work again ;)
