### ISSUE TITLE
add Twitter site

### ISSUE THREAD

**Issue by bunaif** [KhunHtetzNaing/xGetter#4]
we need support Twitter site to get download link mp4, thanks

**Comment by KhunHtetzNaing** [comment]
Ok, bro i will check

**Comment by bunaif** [comment]
thanks

**Comment by Smarpit-Singh** [comment]
> Ok, bro I will check

Hey brother, I got a problem. I really need your help. 
Please contact me on sirakarta22@gmail.com

**Comment by KhunHtetzNaing** [comment]
@Smarpit-Singh done

**Comment by KhunHtetzNaing** [comment]
hey @bunaif , i added twitter,youtube and solidfiles in new version 1.9

**Comment by bunaif** [comment]
hi, thanks brother for add twitter.

**Comment by bunaif** [comment]
i try it with your example work fine, but when try download from tweet with no video app is crashing
