### ISSUE TITLE
I have been suspended in Google play

### ISSUE THREAD

**Issue by x-man93** [KhunHtetzNaing/xGetter#42]
I really liked this library it is easy and very helpful but Google play will suspended you if you use it 
I have been suspended because of it..!

I hope to solve this problem soon

**Comment by KhunHtetzNaing** [comment]
May be google ban google drive and google photos 😪

**Comment by x-man93** [comment]
I will tell you about my experience with your library and Google play..

First, I use the library in my gradle and I have been suspended by Google play

Second, I thought Google play just check gradle and I tried to add library manually as a class in my app but I have been suspended too

In the third time , I tried to remove UpToStream and megaup websites because I thaught may they are the reason because you use JavascriptInterface in these two sites and as I read it may cause security issues 
you can see this 
https://stackoverflow.com/questions/6415882/android-javascriptinterface-security

but also I have been suspended too.

My fourth trail is remove megaup , upstream , Google drive and google photos from the library but I have been suspended too..

I don't know .. Is google recently classified this library as a malware library by its name.. or is there a problem in it..
could you please create new library comply with Google play policy..?

**Comment by hitzhak** [comment]
> May be google ban google drive and google photos 😪

i think it got to do to the way you inject JS to webview ,that way allow it is only via internal asset not via external link since it's open to influence via 3'rd side

**Comment by KhunHtetzNaing** [comment]
@x-man93 @hitzhak 
hello, I released new version 3.0 and I remove the external javascript file and changes class name to LowCostVideo.
I think will work again ;)
