### ISSUE TITLE
gdrive 

### ISSUE THREAD

**Issue by hitzhak** [KhunHtetzNaing/xGetter#43]
response is :
status=fail&hl=en_US&allow_embed=0&ps=docs&partnerid=30&errorcode=2&reason=We%27re+processing+this+video.+Check+back+later+or+download+the+video+now.&timestamp=1590913914670&suberrorcode=9&BASE_URL=https%3A%2F%2Fdrive.google.com%2F

i can play the video with different approach (using download stream ) but on mxPlayer ,trying to find a way to play on exoplayer ,any suggestion ?

**Comment by KhunHtetzNaing** [comment]
fixed, please update to 3.0
